name: Auto build release
on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64, arm]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm
            goos: darwin
          - goarch: arm64
            goos: windows
          - goarch: arm
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.22.2"
          project_path: "./app"
          ldflags: -s -w -extldflags -static
          binary_name: "shy"
          extra_files: README.md app/config.yaml